services:
    devcenter:
        stdin_open: true
        tty: true
        volumes:
            - ${PWD}/dev:${PWD}/dev
        working_dir: ${PWD}/dev
        ports:
            - 1313:1313
        # expose:
        #     - "1313"
        image: nixos/nix
        command:
            # Dev
            - nix-shell
            # Prod
            # - nix-shell prod.nix
            # Cleanup
            # - nix-store --gc

