applications:
    devcenter:
        source:
            root: dev

        stack:
            - nodejs@22
            - nodePackages.npm
            - python312
            - hugo
            - goaccess
        hooks:
            build: |
                npm install 

                if [ -z ${HUGO_ENVIRONMENT+x} ]; then 
                    npm run build:nonprod
                else 
                    if [ "$HUGO_ENVIRONMENT" = "production" ]; then
                        npm run build:prod
                    fi
                fi

                if [ ! -e "${PLATFORM_APP_DIR}/public/search/search.json" ] || [ ! -L "${PLATFORM_APP_DIR}/public/search/search.json" ]; then
                    echo "symlink for search.json doesn't exist. I'll attempt to create it."
                    ln -s -f "${PLATFORM_APP_DIR}/search-sources/search.json" "${PLATFORM_APP_DIR}/public/search/search.json"
                fi
            post_deploy: |
                bash "${PLATFORM_APP_DIR}"/search.sh
                bash "${PLATFORM_APP_DIR}"/purge.sh

        relationships:
            vault_manage:
                service: vault-kms
                endpoint: management
            vault_sign:
                service: vault-kms
                endpoint: sign_and_verify

        web:
            commands:
                start: "node index.js"
            locations:
                /:
                    root: "public"
                    passthru: true
                    index:
                      - index.html
                    scripts: false
                    allow: true
                    expires: 24h
                    rules:
                        \.(css|js|gif|jpe?g|png|ttf|eot|woff2?|otf|cast|mp4|json|yaml|ico|svg?|cast|mp4|json|yaml|svg?|ttf)$:
                            expires: 4w

        # workers:
        #     queue:
        #         commands:
        #             start: |
        #                 cat /var/log/access.log | goaccess --log-format=COMBINED -o public/access/report.html --real-time-html -   

        mounts:
            'search-sources':
                source: storage
            'public/dcxs':
                source: storage

                # cat /var/log/access.log | goaccess --log-format=COMBINED -o public/access/report.html --real-time-html -

        operations:
            update-search-index:
                commands:
                    start: bash "${PLATFORM_APP_DIR}"/search.sh

        crons:
            update-search-index:
                spec: "19 7,19 * * *"
                commands:
                    start: bash "${PLATFORM_APP_DIR}"/search.sh

routes:
    "https://{default}/":
        type: upstream
        primary: true
        upstream: "devcenter:http"
    "https://www.{default}":
        type: redirect
        to: "https://{default}/"

services:
    # The name of the service container. Must be unique within a project.
    vault-kms:
        type: vault-kms:1.12
        configuration:
            endpoints:
                management:
                    - policy: admin
                      key: admin-key
                      type: sign
                sign_and_verify:
                    - policy: sign
                      key: signing-key
                      type: sign
                    - policy: verify
                      key: signing-key
                      type: sign