applications:
    devcenter:
        source:
            root: dev

        stack:
            - nodejs@22
            - nodePackages.npm
            - python312
            - hugo
        hooks:
            build: |
                npm install
                npm run build 
        
        web:
            locations:
                /:
                    root: "public"
                    passthru: true
                    index:
                      - index.html
                    scripts: false
                    allow: true
                    expires: 24h
                    rules:
                        \.(css|js|gif|jpe?g|png|ttf|eot|woff2?|otf|cast|mp4|json|yaml|ico|svg?|cast|mp4|json|yaml|svg?|ttf)$:
                            expires: 4w

routes:
    "https://{default}/":
        type: upstream
        primary: true
        upstream: "devcenter:http"
    "https://www.{default}":
        type: redirect
        to: "https://{default}/"
