applications:
    devcenter:
        source:
            root: dev

        stack:
            - nodejs@22
            - nodePackages.npm
            - python312
            - hugo
        hooks:
            build: |
                npm install 

                if [ -z ${HUGO_ENVIRONMENT+x} ]; then 
                    npm run build:nonprod
                else 
                    if [ "$HUGO_ENVIRONMENT" = "production" ]; then
                        npm run build:prod
                    fi
                fi

                if [ ! -e "${PLATFORM_APP_DIR}/public/search/search.json" ] || [ ! -L "${PLATFORM_APP_DIR}/public/search/search.json" ]; then
                    echo "symlink for search.json doesn't exist. I'll attempt to create it."
                    ln -s -f "${PLATFORM_APP_DIR}/search-sources/search.json" "${PLATFORM_APP_DIR}/public/search/search.json"
                fi
            post_deploy: |
                bash "${PLATFORM_APP_DIR}"/search.sh
                bash "${PLATFORM_APP_DIR}"/purge.sh

        web:
            commands:
                start: "node index.js"
            locations:
                /:
                    root: "public"
                    passthru: true
                    index:
                      - index.html
                    scripts: false
                    allow: true
                    expires: 24h
                    rules:
                        \.(css|js|gif|jpe?g|png|ttf|eot|woff2?|otf|cast|mp4|json|yaml|ico|svg?|cast|mp4|json|yaml|svg?|ttf)$:
                            expires: 4w

        mounts:
            'search-sources':
                source: storage

        operations:
            update-search-index:
                commands:
                    start: bash "${PLATFORM_APP_DIR}"/search.sh

        crons:
          update-search-index:
            spec: 19 7,19 * * *
            commands:
              start: bash "${PLATFORM_APP_DIR}"/search.sh

routes:
    "https://{default}/":
        type: upstream
        primary: true
        upstream: "devcenter:http"
